FROM node:16-alpine
WORKDIR /app/dev
COPY package*.json /app/dev
RUN npm ci

# Copying source files
COPY . /app/dev

# Building app
RUN npm run build

EXPOSE 3000

ENV NEXT_PUBLIC_GOOGLE_ANALYTICS=G-XXXXXXXXXX

# Running the app
CMD ["npm", "run", "dev"]